Adjust LiveChat API Service offering
aaronellington/zendesk-go pull request #25
Opened 2024-01-30 22:27 UTC by equalsgibson

2024-01-30 22:34 UTC, equalsgibson commented
Hey @aaronellington, I've refactored some small bits here and there. I am hoping to continue this, and also propose adding gobwas (ws) for the LiveChat Streaming section

Alternatively, we could try and roll our own WS lib using the std lib - I don't mind either way.

Let me know your thoughts on the above

2024-01-30 23:47 UTC, aaronellington requested changes

2024-01-30 23:47 UTC, aaronellington commented on zendesk/types.go
> +	ChatDepartmentID         uint64
I think we can just got rid of this and use GroupID

2024-01-30 23:47 UTC, aaronellington commented on zendesk/service.go
> +				websocketStreamingService: &WebsocketStreamingService{
Can we rename all these from WebsocketStreamingService to RealTimeChatStreamingService so the exported type is associated with the the chat side of the house and not the ticket/support side of things.

2024-01-30 23:47 UTC, aaronellington commented on zendesk/service.go
> +				restService: &RESTService{
Same with this. Let's call it RealTimeChatRestService.

2024-01-30 23:48 UTC, aaronellington commented
Thanks! Looks pretty good! There is a lot here. I've added a few comments but we will chat about this tomorrow morning. 👍

2024-01-31 14:19 UTC, equalsgibson commented on zendesk/types.go
> +	ChatDepartmentID         uint64
Agreed, changing now - Originally thought that these were distinct (maybe they were at one point?) but they appear to be the same

2024-02-03 23:13 UTC, equalsgibson commented on zendesk/client.go
> +const (
These changes for the consts were required by the linter

2024-02-03 23:18 UTC, equalsgibson commented
Hi @aaronellington, I've added some additional testing. For now, I am planning on leaving the WSS as a stub function (just the service), and will complete the work for that in a separate PR (as it touches a different area of the api). 

I believe that I have made the requested changes to the PR - let me know your thoughts and if I am good to merge

2024-02-08 13:58 UTC, aaronellington approved these changes

2024-02-08 14:37 UTC, merged