Added endpoint for delete users sessions
aaronellington/zendesk-go pull request #34
Opened 2024-05-03 14:57 UTC by RomanGod6

## Changes
* Added a new endpoint for deleting a users session via there ID

2024-05-03 16:07 UTC, equalsgibson commented
Looks good to me - could you please add a unit test for this new func, that shows the expected response from Zendesk (with dummy data in place of any actual usernames or ids?)

2024-05-03 16:14 UTC, equalsgibson commented on zendesk/support_users.go
> +}
Can we move this out of the "User Service" and put it into the "Account Configuration" service?

2024-05-06 12:40 UTC, aaronellington requested changes

2024-05-06 12:40 UTC, aaronellington commented on zendesk/account_configuration_delete_sessions.go
> +// https://developer.zendesk.com/api-reference/ticketing/account-configuration/sessions/#delete-session
this is the correct comment/link? Aren't you calling the bulk delete endpoint?

2024-05-06 12:40 UTC, aaronellington commented on zendesk/account_configuration_delete_sessions.go
> +func (s SessionService) DeleteSession(
```suggestion
func (s SessionService) BulkDelete(
```

2024-05-06 13:08 UTC, merged